name: Test v1.6 (LTS)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/Test.yml'
      - 'Project.toml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [ubuntu-latest, windows-latest]
        experimental: [false]

    steps:
      # Checks-out your repository
      - name: Check out repository
        uses: actions/checkout@latest

      # Set up Julia
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

     # Set up cache
      - name: "Set up cache"
        uses: actions/cache@latest
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      # Build package
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@latest

      # Run the tests
      - name: "Run tests"
        uses: julia-actions/julia-runtest@latest

      # Preprocess Coverage
      - name: "Preprocess Coverage"
        uses: julia-actions/julia-processcoverage@latest

      # Run codecov
      - name: "Run CodeCov"
        uses: codecov/codecov-action@latest
        with:
          file: lcov.info
