name: Run FMIFlux.jl tests

on:
  pull_request:
  push:
    paths:
    - 'src/**'
    - 'test/**'
    - '.github/**'
  

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      # Don't cancel in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        julia-version: ['1.6', '1']
        julia-arch: [x64]
        os: [windows-latest] # ubuntu-latest
        experimental: [false] # true

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v2

      # Set up Julia
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}

     # Set up cache
      - name: "Set up cache"
        uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      # Build FMIFlux.jl package
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1

      # Run the tests
      - name: "Run tests"
        uses: julia-actions/julia-runtest@v1

      # Preprocess Coverage
      - name: "Preprocess Coverage"
        uses: julia-actions/julia-processcoverage@v1

      # Run codecov
      - name: "Run CodeCov"
        uses: codecov/codecov-action@v2
        with:
          file: lcov.info
